name: 🧰 Build Double Commander AppImage with AppImageBuilder

on:
  schedule:
    - cron: '0 4 * * 0'  # Каждое воскресенье в 04:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 📦 Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl desktop-file-utils libglib2.0-0

      - name: 📦 Установить AppImageBuilder
        run: |
          sudo apt install -y python3-pip
          pip3 install appimage-builder

      - name: 🔨 Build Double Commander AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml --skip-test

      - name: 📤 Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DoubleCommander-AppImage
          path: Double_Commander-*-x86_64.AppImage

      - name: 🏷️ Extract Version (Optional)
        id: get_version
        run: |
          FILE=$(ls Double_Commander-*-x86_64.AppImage 2>/dev/null | head -1)
          if [ -n "$FILE" ]; then
            VERSION=$(echo "$FILE" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Не удалось определить версию"
            exit 1
          fi

      - name: 🚀 Create GitHub Release (Optional)
        if: success() && github.event_name == 'schedule'
        uses: softprops/action-gh-release@v2
        with:
          files: Double_Commander-*-x86_64.AppImage
          tag_name: v${{ steps.get_version.outputs.version }}
          body: "Автоматическая сборка Double Commander AppImage через AppImageBuilder"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
